I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 10, in script
    scene workshop with fadein
  File "game/script.rpy", line 10, in <module>
    scene workshop with fadein
NameError: name 'fadein' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 10, in script
    scene workshop with fadein
  File "C:\Users\anais\Downloads\renpy\renpy-8.1.1-sdk\renpy\ast.py", line 1357, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\anais\Downloads\renpy\renpy-8.1.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\anais\Downloads\renpy\renpy-8.1.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 10, in <module>
    scene workshop with fadein
NameError: name 'fadein' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24100702+nightly
Emi VN 1.0
Wed Oct 23 19:38:44 2024
